import type { Player, Team } from './types';

export const IPL_TEAMS: Team[] = [
    { id: 'CSK', name: 'Chennai Super Kings' },
    { id: 'DC', name: 'Delhi Capitals' },
    { id: 'GT', name: 'Gujarat Titans' },
    { id: 'KKR', name: 'Kolkata Knight Riders' },
    { id: 'LSG', name: 'Lucknow Super Giants' },
    { id: 'MI', name: 'Mumbai Indians' },
    { id: 'PBKS', name: 'Punjab Kings' },
    { id: 'RR', name: 'Rajasthan Royals' },
    { id: 'RCB', name: 'Royal Challengers Bengaluru' },
    { id: 'SRH', name: 'Sunrisers Hyderabad' },
];

const RAW_PLAYER_SETS: { setName: string; players: Omit<Player, 'isOverseas'>[] }[] = [
  {
    setName: "SET 1: MARQUEE PLAYERS",
    players: [
      { id: 1, name: "Virat Kohli", role: "Batsman", nationality: "IND", basePrice: 2.0 },
      { id: 2, name: "Rohit Sharma", role: "Batsman", nationality: "IND", basePrice: 2.0 },
      { id: 3, name: "Jasprit Bumrah", role: "Bowler", nationality: "IND", basePrice: 2.0 },
      { id: 4, name: "Hardik Pandya", role: "All-Rounder", nationality: "IND", basePrice: 2.0 },
      { id: 5, name: "MS Dhoni", role: "Wicketkeeper", nationality: "IND", basePrice: 2.0 },
      { id: 6, name: "Ravindra Jadeja", role: "All-Rounder", nationality: "IND", basePrice: 2.0 },
      { id: 7, name: "Pat Cummins", role: "Bowler", nationality: "AUS", basePrice: 2.0 },
      { id: 8, name: "Rashid Khan", role: "Bowler", nationality: "AFG", basePrice: 2.0 },
      { id: 9, name: "Shubman Gill", role: "Batsman", nationality: "IND", basePrice: 2.0 },
      { id: 10, name: "Sanju Samson", role: "Wicketkeeper", nationality: "IND", basePrice: 2.0 },
      { id: 11, name: "Suryakumar Yadav", role: "Batsman", nationality: "IND", basePrice: 2.0 },
      { id: 12, name: "Nicholas Pooran", role: "Wicketkeeper", nationality: "WI", basePrice: 2.0 },
      { id: 13, name: "Jos Buttler", role: "Wicketkeeper", nationality: "ENG", basePrice: 2.0 },
      { id: 14, name: "KL Rahul", role: "Wicketkeeper", nationality: "IND", basePrice: 2.0 },
      { id: 15, name: "Mohammed Shami", role: "Bowler", nationality: "IND", basePrice: 2.0 },
      { id: 16, name: "Mitchell Starc", role: "Bowler", nationality: "AUS", basePrice: 2.0 },
      { id: 20, name: "Travis Head", role: "Batsman", nationality: "AUS", basePrice: 2.0 },
    ],
  },
  {
    setName: "SET 2: TOP-ORDER BATTERS",
    players: [
      { id: 21, name: "Yashasvi Jaiswal", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 22, name: "Ruturaj Gaikwad", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 23, name: "Abhishek Sharma", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 24, name: "Sai Sudharsan", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 25, name: "Rajat Patidar", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 26, name: "Prithvi Shaw", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 27, name: "Devdutt Padikkal", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 28, name: "Shikhar Dhawan", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 29, name: "Faf du Plessis", role: "Batsman", nationality: "SA", basePrice: 1.0 },
      { id: 30, name: "Aiden Markram", role: "Batsman", nationality: "SA", basePrice: 1.0 },
      { id: 31, name: "Harry Brook", role: "Batsman", nationality: "ENG", basePrice: 1.0 },
      { id: 32, name: "Rachin Ravindra", role: "Batsman", nationality: "NZ", basePrice: 1.0 },
      { id: 33, name: "Will Jacks", role: "Batsman", nationality: "ENG", basePrice: 1.0 },
      { id: 34, name: "Mayank Agarwal", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 35, name: "Jason Roy", role: "Batsman", nationality: "ENG", basePrice: 1.0 },
      { id: 37, name: "Dawid Malan", role: "Batsman", nationality: "ENG", basePrice: 1.0 },
      { id: 38, name: "Rilee Rossouw", role: "Batsman", nationality: "SA", basePrice: 1.0 },
      { id: 39, name: "Reeza Hendricks", role: "Batsman", nationality: "SA", basePrice: 1.0 },
      { id: 40, name: "Nitish Rana", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 41, name: "Rahul Tripathi", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 42, name: "Manish Pandey", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 43, name: "Karun Nair", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 44, name: "Angkrish Raghuvanshi", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 45, name: "Sameer Rizvi", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 46, name: "Nehal Wadhera", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 47, name: "Shahrukh Khan", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 48, name: "Abhimanyu Easwaran", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 49, name: "Priyansh Arya", role: "Batsman", nationality: "IND", basePrice: 1.0 },
      { id: 50, name: "Shubham Dubey", role: "Batsman", nationality: "IND", basePrice: 1.0 },
    ],
  },
  {
    setName: "SET 3: MIDDLE-ORDER / FINISHER BATTERS",
    players: [
      { id: 51, name: "Rinku Singh", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 52, name: "Shimron Hetmyer", role: "Batsman", nationality: "WI", basePrice: 0.75 },
      { id: 53, name: "Shivam Dube", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 54, name: "Tilak Varma", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 55, name: "Ayush Badoni", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 56, name: "Tim David", role: "Batsman", nationality: "AUS", basePrice: 0.75 },
      { id: 57, name: "Glenn Phillips", role: "Batsman", nationality: "NZ", basePrice: 0.75 },
      { id: 58, name: "Rovman Powell", role: "Batsman", nationality: "WI", basePrice: 0.75 },
      { id: 59, name: "Sherfane Rutherford", role: "Batsman", nationality: "WI", basePrice: 0.75 },
      { id: 60, name: "Abdul Samad", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 61, name: "Sarfaraz Khan", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 62, name: "Riyan Parag", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 63, name: "Rahul Tewatia", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 64, name: "Shashank Singh", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 65, name: "Nitish Kumar Reddy", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 66, name: "Abhishek Porel", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 67, name: "Dhruv Jurel", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 68, name: "KS Bharat", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 69, name: "Finn Allen", role: "Batsman", nationality: "NZ", basePrice: 0.75 },
      { id: 70, name: "Ibrahim Zadran", role: "Batsman", nationality: "AFG", basePrice: 0.75 },
      { id: 71, name: "Brandon King", role: "Batsman", nationality: "WI", basePrice: 0.75 },
      { id: 72, name: "James Vince", role: "Batsman", nationality: "ENG", basePrice: 0.75 },
      { id: 73, name: "Ashton Turner", role: "Batsman", nationality: "AUS", basePrice: 0.75 },
      { id: 74, name: "Rassie van der Dussen", role: "Batsman", nationality: "SA", basePrice: 0.75 },
      { id: 75, name: "Harry Tector", role: "Batsman", nationality: "IRE", basePrice: 0.75 },
      { id: 76, name: "Mark Chapman", role: "Batsman", nationality: "NZ", basePrice: 0.75 },
      { id: 77, name: "Sam Hain", role: "Batsman", nationality: "ENG", basePrice: 0.75 },
      { id: 78, name: "Tom Kohler-Cadmore", role: "Batsman", nationality: "ENG", basePrice: 0.75 },
      { id: 79, name: "Musheer Khan", role: "Batsman", nationality: "IND", basePrice: 0.75 },
      { id: 80, name: "Raj Angad Bawa", role: "Batsman", nationality: "IND", basePrice: 0.75 },
    ],
  },
  {
    setName: "SET 4: WICKETKEEPERS",
    players: [
      { id: 81, name: "Heinrich Klaasen", role: "Wicketkeeper", nationality: "SA", basePrice: 0.5 },
      { id: 82, name: "Tristan Stubbs", role: "Wicketkeeper", nationality: "SA", basePrice: 0.5 },
      { id: 83, name: "Josh Inglis", role: "Wicketkeeper", nationality: "AUS", basePrice: 0.5 },
      { id: 84, name: "Kusal Mendis", role: "Wicketkeeper", nationality: "SL", basePrice: 0.5 },
      { id: 85, name: "Philip Salt", role: "Wicketkeeper", nationality: "ENG", basePrice: 0.5 },
      { id: 86, name: "Sam Billings", role: "Wicketkeeper", nationality: "ENG", basePrice: 0.5 },
      { id: 87, name: "Shai Hope", role: "Wicketkeeper", nationality: "WI", basePrice: 0.5 },
      { id: 88, name: "Ben Duckett", role: "Wicketkeeper", nationality: "ENG", basePrice: 0.5 },
      { id: 89, name: "Jitesh Sharma", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 90, name: "Ishan Kishan", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 91, name: "Ryan Rickelton", role: "Wicketkeeper", nationality: "SA", basePrice: 0.5 },
      { id: 92, name: "Urvil Patel", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 93, name: "Kumar Kushagra", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 94, name: "Baba Indrajith", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 95, name: "Robin Minz", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 96, name: "Harvik Desai", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 97, name: "Mohit Ahlawat", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 98, name: "Vishnu Solanki", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 99, name: "Ricky Bhui", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
      { id: 100, name: "Anuj Rawat", role: "Wicketkeeper", nationality: "IND", basePrice: 0.5 },
    ],
  },
  {
    setName: "SET 5: ALL-ROUNDERS",
    players: [
      { id: 101, name: "Axar Patel", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 102, name: "Sunil Narine", role: "All-Rounder", nationality: "WI", basePrice: 0.75 },
      { id: 103, name: "Andre Russell", role: "All-Rounder", nationality: "WI", basePrice: 0.75 },
      { id: 104, name: "Marcus Stoinis", role: "All-Rounder", nationality: "AUS", basePrice: 0.75 },
      { id: 105, name: "Liam Livingstone", role: "All-Rounder", nationality: "ENG", basePrice: 0.75 },
      { id: 106, name: "Jason Holder", role: "All-Rounder", nationality: "WI", basePrice: 0.75 },
      { id: 107, name: "Shardul Thakur", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 108, name: "Washington Sundar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 109, name: "Krunal Pandya", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 110, name: "Deepak Hooda", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 111, name: "Marco Jansen", role: "All-Rounder", nationality: "SA", basePrice: 0.75 },
      { id: 112, name: "Wanindu Hasaranga", role: "All-Rounder", nationality: "SL", basePrice: 0.75 },
      { id: 113, name: "Shahbaz Ahmed", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 114, name: "Daryl Mitchell", role: "All-Rounder", nationality: "NZ", basePrice: 0.75 },
      { id: 115, name: "Michael Bracewell", role: "All-Rounder", nationality: "NZ", basePrice: 0.75 },
      { id: 116, name: "Fabian Allen", role: "All-Rounder", nationality: "WI", basePrice: 0.75 },
      { id: 117, name: "James Neesham", role: "All-Rounder", nationality: "NZ", basePrice: 0.75 },
      { id: 118, name: "Daniel Sams", role: "All-Rounder", nationality: "AUS", basePrice: 0.75 },
      { id: 119, name: "Vijay Shankar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 120, name: "Ramandeep Singh", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 121, name: "Arshin Kulkarni", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 122, name: "Shams Mulani", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 123, name: "Jalaj Saxena", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 124, name: "Swapnil Singh", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 125, name: "Mitchell Santner", role: "All-Rounder", nationality: "NZ", basePrice: 0.75 },
      { id: 126, name: "Moeen Ali", role: "All-Rounder", nationality: "ENG", basePrice: 0.75 },
      { id: 127, name: "Romario Shepherd", role: "All-Rounder", nationality: "WI", basePrice: 0.75 },
      { id: 128, name: "Azmatullah Omarzai", role: "All-Rounder", nationality: "AFG", basePrice: 0.75 },
      { id: 129, name: "Sikandar Raza", role: "All-Rounder", nationality: "ZIM", basePrice: 0.75 },
      { id: 130, name: "David Wiese", role: "All-Rounder", nationality: "NAM", basePrice: 0.75 },
      { id: 131, name: "Sean Abbott", role: "All-Rounder", nationality: "AUS", basePrice: 0.75 },
      { id: 132, name: "Chris Woakes", role: "All-Rounder", nationality: "ENG", basePrice: 0.75 },
      { id: 133, name: "Cameron Green", role: "All-Rounder", nationality: "AUS", basePrice: 0.75 },
      { id: 134, name: "Kyle Jamieson", role: "All-Rounder", nationality: "NZ", basePrice: 0.75 },
      { id: 135, name: "Rishi Dhawan", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 136, name: "Venkatesh Iyer", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 137, name: "Shivam Mavi", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 138, name: "Lalit Yadav", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 139, name: "Harpreet Brar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 140, name: "Anukul Roy", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 141, name: "Rajvardhan Hangargekar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 142, name: "Nishant Sindhu", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 143, name: "Arjun Tendulkar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 144, name: "Akash Deep", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 145, name: "Manoj Bhandage", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 146, name: "Mohit Rathee", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 147, name: "Saurabh Kumar", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 148, name: "Himanshu Chauhan", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
      { id: 149, name: "Pulkit Narang", role: "All-Rounder", nationality: "IND", basePrice: 0.75 },
    ],
  },
  {
    setName: "SET 6: FAST BOWLERS",
    players: [
      { id: 150, name: "Mohammed Siraj", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 151, name: "Arshdeep Singh", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 152, name: "Prasidh Krishna", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 153, name: "Umran Malik", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 154, name: "Avesh Khan", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 155, name: "Mukesh Kumar", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 156, name: "Yash Dayal", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 157, name: "Harshit Rana", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 158, name: "Mohsin Khan", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 159, name: "Mayank Yadav", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 160, name: "Akash Singh", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 161, name: "Navdeep Saini", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 162, name: "Khaleel Ahmed", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 163, name: "T Natarajan", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 164, name: "Ishant Sharma", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 165, name: "Deepak Chahar", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 166, name: "Lockie Ferguson", role: "Bowler", nationality: "NZ", basePrice: 0.5 },
      { id: 167, name: "Josh Hazlewood", role: "Bowler", nationality: "AUS", basePrice: 0.5 },
      { id: 168, name: "Gerald Coetzee", role: "Bowler", nationality: "SA", basePrice: 0.5 },
      { id: 169, name: "Kagiso Rabada", role: "Bowler", nationality: "SA", basePrice: 0.5 },
      { id: 170, name: "Lungi Ngidi", role: "Bowler", nationality: "SA", basePrice: 0.5 },
      { id: 171, name: "Anrich Nortje", role: "Bowler", nationality: "SA", basePrice: 0.5 },
      { id: 172, name: "Alzarri Joseph", role: "Bowler", nationality: "WI", basePrice: 0.5 },
      { id: 173, name: "Adam Milne", role: "Bowler", nationality: "NZ", basePrice: 0.5 },
      { id: 174, name: "Tim Southee", role: "Bowler", nationality: "NZ", basePrice: 0.5 },
      { id: 175, name: "Reece Topley", role: "Bowler", nationality: "ENG", basePrice: 0.5 },
      { id: 176, name: "Chris Jordan", role: "Bowler", nationality: "ENG", basePrice: 0.5 },
      { id: 177, name: "Mustafizur Rahman", role: "Bowler", nationality: "BAN", basePrice: 0.5 },
      { id: 178, name: "Dilshan Madushanka", role: "Bowler", nationality: "SL", basePrice: 0.5 },
      { id: 179, name: "Spencer Johnson", role: "Bowler", nationality: "AUS", basePrice: 0.5 },
      { id: 180, name: "Dominic Drakes", role: "Bowler", nationality: "WI", basePrice: 0.5 },
      { id: 181, name: "Blessing Muzarabani", role: "Bowler", nationality: "ZIM", basePrice: 0.5 },
      { id: 182, name: "Obed McCoy", role: "Bowler", nationality: "WI", basePrice: 0.5 },
      { id: 183, name: "Yudhvir Singh", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 184, name: "Kartik Tyagi", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 185, name: "Vaibhav Arora", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 186, name: "Akash Madhwal", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 187, name: "Vidwath Kaverappa", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 188, name: "Anshul Kamboj", role: "Bowler", nationality: "IND", basePrice: 0.5 },
      { id: 189, name: "Raj Limbani", role: "Bowler", nationality: "IND", basePrice: 0.5 },
    ],
  },
  {
    setName: "SET 7: SPIN BOWLERS",
    players: [
      { id: 190, name: "Kuldeep Yadav", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 191, name: "Yuzvendra Chahal", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 192, name: "Ravi Bishnoi", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 193, name: "Varun Chakaravarthy", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 194, name: "Rahul Chahar", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 195, name: "Piyush Chawla", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 196, name: "Amit Mishra", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 197, name: "Murugan Ashwin", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 198, name: "Noor Ahmad", role: "Bowler", nationality: "AFG", basePrice: 0.3 },
      { id: 199, name: "Tabraiz Shamsi", role: "Bowler", nationality: "SA", basePrice: 0.3 },
      { id: 200, name: "Adam Zampa", role: "Bowler", nationality: "AUS", basePrice: 0.3 },
      { id: 201, name: "Mujeeb Ur Rahman", role: "Bowler", nationality: "AFG", basePrice: 0.3 },
      { id: 202, name: "Keshav Maharaj", role: "Bowler", nationality: "SA", basePrice: 0.3 },
      { id: 203, name: "Maheesh Theekshana", role: "Bowler", nationality: "SL", basePrice: 0.3 },
      { id: 204, name: "Shreyas Gopal", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 205, name: "Sai Kishore", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 206, name: "Mayank Markande", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 207, name: "Suyash Sharma", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 208, name: "Manav Suthar", role: "Bowler", nationality: "IND", basePrice: 0.3 },
      { id: 209, name: "Himanshu Sharma", role: "Bowler", nationality: "IND", basePrice: 0.3 },
    ],
  },
  {
    setName: "SET 8: UNCAPPED INDIAN PLAYERS",
    players: [
      { id: 210, name: "Sameer Rizvi", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 211, name: "Angkrish Raghuvanshi", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 212, name: "Musheer Khan", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 213, name: "Priyansh Arya", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 214, name: "Yash Dhull", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 215, name: "Naman Dhir", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 216, name: "Kumar Kushagra", role: "Wicketkeeper", nationality: "IND", basePrice: 0.2 },
      { id: 217, name: "Harshit Rana", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 218, name: "Mayank Yadav", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 219, name: "Anshul Kamboj", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 220, name: "Rajvardhan Hangargekar", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 221, name: "Vidwath Kaverappa", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 222, name: "Akash Madhwal", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 223, name: "Mohit Rathee", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 224, name: "Manav Suthar", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 225, name: "Arjun Tendulkar", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 226, name: "Nishant Sindhu", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 227, name: "Saurabh Kumar", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 228, name: "Ricky Bhui", role: "Wicketkeeper", nationality: "IND", basePrice: 0.2 },
      { id: 229, name: "Urvil Patel", role: "Wicketkeeper", nationality: "IND", basePrice: 0.2 },
      { id: 230, name: "Robin Minz", role: "Wicketkeeper", nationality: "IND", basePrice: 0.2 },
      { id: 231, name: "Mohammad Arshad Khan", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 232, name: "Shivam Singh", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 233, name: "Vasu Vats", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 234, name: "Pulkit Narang", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 235, name: "Raghu Sharma", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 236, name: "Siddharth Desai", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 237, name: "Abhinav Manohar", role: "Batsman", nationality: "IND", basePrice: 0.2 },
      { id: 238, name: "Vishnu Vinod", role: "Wicketkeeper", nationality: "IND", basePrice: 0.2 },
      { id: 239, name: "Rajat Dey", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 240, name: "Akash Vasisht", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 241, name: "Swapnil Singh", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 242, name: "Himanshu Chauhan", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 243, name: "Kartik Tyagi", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 244, name: "Vaibhav Arora", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 245, name: "Sakib Hussain", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 246, name: "Mukesh Kumar", role: "Bowler", nationality: "IND", basePrice: 0.2 },
      { id: 247, name: "Yuvraj Chaudhary", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 248, name: "Manoj Bhandage", role: "All-Rounder", nationality: "IND", basePrice: 0.2 },
      { id: 249, name: "Rohit Kumar", role: "Batsman", nationality: "IND", basePrice: 0.2 },
    ]
  }
];

export const PLAYER_SETS: { setName: string; players: Player[] }[] = RAW_PLAYER_SETS.map(set => ({
    ...set,
    players: set.players.map(player => ({
        ...player,
        isOverseas: player.nationality !== 'IND'
    }))
}));


export const INITIAL_BUDGET = 120.0;
export const MAX_PLAYERS_PER_TEAM = 25;
export const AUCTION_TIMER_SECONDS = 10;

    